### ISSUE TITLE
vame.train_model error

### ISSUE THREAD

**Issue by geocc-ops** [EthoML/VAME#120]
Hi. I hope all is well. I am new to using pose estimators and wanted to try vame. I am currently following the guide that you have posted on the page here: https://ethoml.github.io/VAME/docs/getting_started/installation. I installed vame using pip where the vame I am using is vame-py. I seem to not have access to the video examples for the first demo. Is there a way I can download it? In addition, I am using a different set of videos, but it seems that when I train the model I get this output during vame.train_model(config):

2024-12-13 10:42:15.639 INFO  --- [MainThread] vame.model.rnn_vae : 549 : Train Variational Autoencoder - model name: VAME 

2024-12-13 10:42:15.640 INFO  --- [MainThread] vame.model.rnn_vae : 564 : Using CUDA
2024-12-13 10:42:15.641 INFO  --- [MainThread] vame.model.rnn_vae : 565 : GPU active: True
2024-12-13 10:42:15.641 INFO  --- [MainThread] vame.model.rnn_vae : 566 : GPU used: NVIDIA RTX A2000
2024-12-13 10:42:15.641 INFO  --- [MainThread] vame.model.rnn_vae : 616 : Latent Dimensions: 30, Time window: 30, Batch Size: 256, Beta: 1, lr: 0.0005

2024-12-13 10:42:15.682 INFO  --- [MainThread] vame.model.dataloader : 73 : Initialize train data. Datapoints 675
2024-12-13 10:42:15.684 INFO  --- [MainThread] vame.model.dataloader : 75 : Initialize test data. Datapoints 75
2024-12-13 10:42:15.684 INFO  --- [MainThread] vame.model.rnn_vae : 736 : Scheduler step size: 100, Scheduler gamma: 0.20

2024-12-13 10:42:15.684 INFO  --- [MainThread] vame.model.rnn_vae : 755 : Start training... 
Training Model:   0%|          | 0/499 [00:00<?, ?epoch/s]2024-12-13 10:42:16.81 INFO  --- [MainThread] vame.model.rnn_vae : 374 : Train loss: 208575.531, MSE-Loss: 138919.523, MSE-Future-Loss 69656.008, KL-Loss: 0.000, Kmeans-Loss: 0.000, weight: 0.00
Training Model:   0%|          | 0/499 [00:00<?, ?epoch/s]
2024-12-13 10:42:16.91 ERROR --- [MainThread] vame.model.rnn_vae : 939 : An error occurred: float division by zero
Traceback (most recent call last):
  File "c:\Users\geocc\anaconda3\envs\VAME\Lib\site-packages\vame\model\rnn_vae.py", line 783, in train_model
    current_loss, test_loss, test_list = test(
                                         ^^^^^
  File "c:\Users\geocc\anaconda3\envs\VAME\Lib\site-packages\vame\model\rnn_vae.py", line 490, in test
    test_loss / idx,
    ~~~~~~~~~~^~~~~
ZeroDivisionError: float division by zero
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Cell In[14], [line 2](vscode-notebook-cell:?execution_count=14&line=2)
      [1](vscode-notebook-cell:?execution_count=14&line=1) # Step 2: Train VAME
----> [2](vscode-notebook-cell:?execution_count=14&line=2) vame.train_model(config)

File c:\Users\geocc\anaconda3\envs\VAME\Lib\site-packages\vame\schemas\states.py:230, in save_state.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    [228](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/schemas/states.py:228) except Exception as e:
    [229](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/schemas/states.py:229)     _save_state(kwargs_model, function_name, state=StatesEnum.failed)
--> [230](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/schemas/states.py:230)     raise e
    [231](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/schemas/states.py:231) except KeyboardInterrupt as e:
    [232](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/schemas/states.py:232)     _save_state(kwargs_model, function_name, state=StatesEnum.aborted)

File c:\Users\geocc\anaconda3\envs\VAME\Lib\site-packages\vame\schemas\states.py:225, in save_state.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    [223](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/schemas/states.py:223) _save_state(kwargs_model, function_name, state=StatesEnum.running)
    [224](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/schemas/states.py:224) try:
--> [225](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/schemas/states.py:225)     func_output = func(*args, **kwargs)
    [226](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/schemas/states.py:226)     _save_state(kwargs_model, function_name, state=StatesEnum.success)
    [227](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/schemas/states.py:227)     return func_output

File c:\Users\geocc\anaconda3\envs\VAME\Lib\site-packages\vame\model\rnn_vae.py:940, in train_model(config, save_logs)
    [938](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/model/rnn_vae.py:938) except Exception as e:
    [939](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/model/rnn_vae.py:939)     logger.exception(f"An error occurred: {e}")
--> [940](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/model/rnn_vae.py:940)     raise e
    [941](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/model/rnn_vae.py:941) finally:
...
    [494](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/model/rnn_vae.py:494)     )
    [495](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/model/rnn_vae.py:495) )
    [496](file:///C:/Users/geocc/anaconda3/envs/VAME/Lib/site-packages/vame/model/rnn_vae.py:496) return mse_loss / idx, test_loss / idx, kl_weight * kmeans_losses

ZeroDivisionError: float division by zero


I'm not sure how to go about this.
best,

**Comment by geocc-ops** [comment]
Actually, I found out that I need to decrease the batch size. However, I don't know where to download the example for the video and csv files.

**Comment by luiztauffer** [comment]
hi @geocc-ops , I'm sorry for the delay in responding, we've been working on significant changes to the package
since you seem to have solved your problem, I'm closing this issue.
Regarding the sample data, we have a new convenient way to download sample data, see it here: https://ethoml.github.io/VAME/docs/getting_started/step_by_step#0-optional-download-input-data
